apiVersion: v1
kind: Service
metadata:
  name: javawebapp-svc
spec:
  selector:
     app: javawebapp
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetport: 9090
  type: LoadBalancer
